// Auto-generated by update_hero.sh — do not edit manually
// Add/remove images in Imagens/hero/ then run: bash update_hero.sh

const heroImages = [
    'Imagens/hero/IMG_1230 2.webp',
    'Imagens/hero/IMG_1.webp',
    'Imagens/hero/IMG_2.webp',
    'Imagens/hero/IMG_3.webp',
    'Imagens/hero/IMG_4.webp',
    'Imagens/hero/P1510576.webp',
    'Imagens/hero/P1510581.webp',
    'Imagens/hero/P1510587.webp',
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { heroImages };
} else {
    window.heroImages = heroImages;
}
