#!/bin/bash
# Run this script whenever you add or remove images from Imagens/hero/
# It will automatically update the hero carousel.

HERO_DIR="Imagens/hero"
OUTPUT="js/hero_images.js"

# Find all image files sorted by name
images=$(find "$HERO_DIR" -maxdepth 1 -type f \( -iname "*.webp" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort)

if [ -z "$images" ]; then
  echo "No images found in $HERO_DIR"
  exit 1
fi

# Build the JS array
echo "// Auto-generated by update_hero.sh — do not edit manually" > "$OUTPUT"
echo "// Add/remove images in Imagens/hero/ then run: bash update_hero.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "const heroImages = [" >> "$OUTPUT"

while IFS= read -r img; do
  echo "    '${img}'," >> "$OUTPUT"
done <<< "$images"

echo "];" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "if (typeof module !== 'undefined' && module.exports) {" >> "$OUTPUT"
echo "    module.exports = { heroImages };" >> "$OUTPUT"
echo "} else {" >> "$OUTPUT"
echo "    window.heroImages = heroImages;" >> "$OUTPUT"
echo "}" >> "$OUTPUT"

count=$(echo "$images" | wc -l)
echo "Done — $count image(s) added to hero carousel."
